# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-19 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('service', models.CharField(choices=[('CHURA PAYPAL TO M-PESA', 'Chura Paypal to M-PESA'), ('CHURA BUY AIRTIME', 'Chura Buy Airtime'), ('CHURA BUY DATA', 'Chura Buy Data'), ('CHURA BULK AIRTIME', 'Chura Bulk Airtime'), ('CHURA AIRTIME FOR CASH', 'Chura Airtime for Cash')], max_length=50)),
                ('complaint', models.CharField(max_length=500)),
                ('department', models.CharField(choices=[('CUSTOMER CARE', 'Customer Care'), ('SALES', 'Sales'), ('DESIGN', 'Design'), ('DEVELOPMENT', 'Development'), ('MAINTENANCE', 'Maintenance')], max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='Pending', max_length=10)),
                ('comment', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
